CREATE TABLE Book (
    id STRING(1024) NOT NULL,
    title STRING(1024) NOT NULL,
    author STRING(1024) NOT NULL
) PRIMARY KEY (id);

CREATE TABLE User (
    id STRING(1024) NOT NULL,
    name STRING(1024) NOT NULL,
    email STRING(1024) NOT NULL,
    status STRING(1024) NOT NULL
) PRIMARY KEY (id);